In [1]:
import tensorflow as tf # tested with 1.14.0
from keras.models import Sequential # feed forward training - each node is linked with it`s predecesor
from keras.layers import Dense # nodes are fully connected across the entire NN
import numpy
import pandas as pd
#from google.colab import files
#uploaded=files.upload()

In [2]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
model=Sequential() # commences with creating the structure of the NN, layers are connected from left to right

In [5]:
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(20,activation='relu')) # hidden layer -01
model.add(Dense(20,activation='relu')) # hidden layer -02
model.add(Dense(22,activation='relu')) # hidden layer -03
model.add(Dense(1,activation='sigmoid')) # output layer

D:\Python_DataScience\25.2\nibm_nic_env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [6]:
tf.keras.utils.plot_model(model, show_shapes=True, show_layer_names=False)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [7]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) # configuring your back-propergation execution

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [8]:
inputs = df.drop(['Outcome'],axis='columns') # independant dataset, excluding the dependent attibute
inputs

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [9]:
target=df.Outcome # dependant attribute

In [13]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in d:\python_datascience\25.2\nibm_nic_env\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 281.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 325.1 kB/s eta 0:00:00
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/36.5 MB 1.8 MB/s eta 0:00:21
   ---------------------------------------- 0.3/36.5 MB 2.5 MB/s eta 0:00:15
    --------------------------------------- 0.6/36.5 MB 3.6 MB/s eta 0:00:10
    --------------------------------------- 0.8/36.5 MB 3.7 MB/s eta 0:00:10
   - -------------------------------------- 1.2/36.5 MB 4.4 MB/s eta 0:00:09
   - -------------------------------------- 1.6/36.5 MB 5.1 MB/s eta 0:00:07
   -- ------------------------------------- 2.0/36.5 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.5/36.5 MB 6.2 MB/s eta 0:00:06
   --- ------------------------------------ 2.9/36.5 MB 6.4 MB/s eta 0:00:06
   --- ------------------------------------ 3.5/36.5 MB 6.9 MB/s eta 0:00:05
   ---- ----------------------------------- 3.9/36.5 MB 7.2 MB/s eta 0:00:05
   ---- ----------------------------------- 4.1/36.5 MB 6.9 MB/s eta 0:00:05
   ----- ---------------------------------- 4.7/36.5 MB 7.3 MB/s eta 0:00:05
   ----- ---------------------------------- 5.3/36.5 MB 7.5 MB/s eta 0:00:05
   ----- ---------------------------------- 5.5/36.5 MB 7.3 MB/s eta 0:00:05
   ------ --------------------------------- 6.0/36.5 MB 7.5 MB/s eta 0:00:05
   ------- -------------------------------- 6.7/36.5 MB 8.0 MB/s eta 0:00:04
   -------- ------------------------------- 7.3/36.5 MB 8.2 MB/s eta 0:00:04
   -------- ------------------------------- 8.0/36.5 MB 8.5 MB/s eta 0:00:04
   --------- ------------------------------ 8.3/36.5 MB 8.6 MB/s eta 0:00:04
   --------- ------------------------------ 8.8/36.5 MB 8.6 MB/s eta 0:00:04
   ---------- ----------------------------- 9.2/36.5 MB 8.6 MB/s eta 0:00:04
   ---------- ----------------------------- 9.2/36.5 MB 8.6 MB/s eta 0:00:04
   ---------- ----------------------------- 9.5/36.5 MB 8.2 MB/s eta 0:00:04
   ---------- ----------------------------- 9.9/36.5 MB 8.2 MB/s eta 0:00:04
   ----------- ---------------------------- 10.4/36.5 MB 8.7 MB/s eta 0:00:03
   ----------- ---------------------------- 10.8/36.5 MB 9.0 MB/s eta 0:00:03
   ------------ --------------------------- 11.2/36.5 MB 9.1 MB/s eta 0:00:03
   ------------ --------------------------- 11.5/36.5 MB 9.2 MB/s eta 0:00:03
   ------------ --------------------------- 11.9/36.5 MB 9.2 MB/s eta 0:00:03
   ------------- -------------------------- 12.1/36.5 MB 9.1 MB/s eta 0:00:03
   ------------- -------------------------- 12.3/36.5 MB 8.6 MB/s eta 0:00:03
   ------------- -------------------------- 12.7/36.5 MB 8.5 MB/s eta 0:00:03
   -------------- ------------------------- 13.0/36.5 MB 8.5 MB/s eta 0:00:03
   -------------- ------------------------- 13.1/36.5 MB 8.4 MB/s eta 0:00:03
   -------------- ------------------------- 13.4/36.5 MB 8.0 MB/s eta 0:00:03
   -------------- ------------------------- 13.7/36.5 MB 7.9 MB/s eta 0:00:03
   --------------- ------------------------ 14.0/36.5 MB 7.7 MB/s eta 0:00:03
   --------------- ------------------------ 14.3/36.5 MB 7.9 MB/s eta 0:00:03
   --------------- ------------------------ 14.6/36.5 MB 7.9 MB/s eta 0:00:03
   ---------------- ----------------------- 14.8/36.5 MB 7.7 MB/s eta 0:00:03
   ---------------- ----------------------- 15.1/36.5 MB 7.6 MB/s eta 0:00:03
   ---------------- ----------------------- 15.4/36.5 MB 7.4 MB/s eta 0:00:03
   ----------------- ---------------------- 15.7/36.5 MB 7.4 MB/s eta 0:00:03
   ----------------- ---------------------- 15.7/36.5 MB 7.4 MB/s eta 0:00:03
   ----------------- ---------------------- 15.8/36.5 MB 7.0 MB/s eta 0:00:03
   ----------------- ---------------------- 15.8/36.5 MB 7.0 MB/s eta 0:00:03
   ----------------- ---------------------- 16.0/36.5 MB 6.7 MB/s eta 0:00:04
   ------------------ --------------------- 16.5/36.5 MB 6.6 MB/s eta 0:00:04
   ------------------ --------------------- 16.8/36.5 MB 6.5 MB/s eta 0:00:04
   ------------------ --------------------- 17.3/36.5 MB 6.4 MB/s eta 0:00:04
   ------------------- -------------------- 17.7/36.5 MB 6.4 MB/s eta 0:00:03
   ------------------- -------------------- 18.3/36.5 MB 6.4 MB/s eta 0:00:03
   -------------------- ------------------- 18.7/36.5 MB 6.5 MB/s eta 0:00:03
   -------------------- ------------------- 19.0/36.5 MB 6.4 MB/s eta 0:00:03
   --------------------- ------------------ 19.3/36.5 MB 6.4 MB/s eta 0:00:03
   --------------------- ------------------ 19.7/36.5 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 20.1/36.5 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 20.6/36.5 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 20.6/36.5 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 20.6/36.5 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 20.7/36.5 MB 6.0 MB/s eta 0:00:03
   ---------------------- ----------------- 21.0/36.5 MB 6.0 MB/s eta 0:00:03
   ----------------------- ---------------- 21.4/36.5 MB 6.0 MB/s eta 0:00:03
   ----------------------- ---------------- 21.6/36.5 MB 6.0 MB/s eta 0:00:03
   ------------------------ --------------- 22.0/36.5 MB 5.9 MB/s eta 0:00:03
   ------------------------ --------------- 22.2/36.5 MB 6.0 MB/s eta 0:00:03
   ------------------------ --------------- 22.6/36.5 MB 6.1 MB/s eta 0:00:03
   ------------------------- -------------- 23.1/36.5 MB 6.1 MB/s eta 0:00:03
   ------------------------- -------------- 23.5/36.5 MB 6.3 MB/s eta 0:00:03
   -------------------------- ------------- 23.9/36.5 MB 6.4 MB/s eta 0:00:02
   -------------------------- ------------- 24.1/36.5 MB 6.2 MB/s eta 0:00:03
   -------------------------- ------------- 24.6/36.5 MB 6.4 MB/s eta 0:00:02
   --------------------------- ------------ 25.2/36.5 MB 6.7 MB/s eta 0:00:02
   ---------------------------- ----------- 25.9/36.5 MB 7.3 MB/s eta 0:00:02
   ----------------------------- ---------- 26.6/36.5 MB 7.9 MB/s eta 0:00:02
   ----------------------------- ---------- 27.2/36.5 MB 8.1 MB/s eta 0:00:02
   ------------------------------ --------- 27.9/36.5 MB 8.1 MB/s eta 0:00:02
   ------------------------------- -------- 28.5/36.5 MB 8.2 MB/s eta 0:00:01
   ------------------------------- -------- 29.0/36.5 MB 8.2 MB/s eta 0:00:01
   -------------------------------- ------- 29.7/36.5 MB 8.7 MB/s eta 0:00:01
   --------------------------------- ------ 30.3/36.5 MB 8.8 MB/s eta 0:00:01
   --------------------------------- ------ 30.7/36.5 MB 8.8 MB/s eta 0:00:01
   ---------------------------------- ----- 31.1/36.5 MB 10.1 MB/s eta 0:00:01
   ---------------------------------- ----- 31.6/36.5 MB 10.2 MB/s eta 0:00:01
   ----------------------------------- ---- 32.1/36.5 MB 10.4 MB/s eta 0:00:01
   ----------------------------------- ---- 32.5/36.5 MB 10.7 MB/s eta 0:00:01
   ------------------------------------ --- 33.1/36.5 MB 10.9 MB/s eta 0:00:01
   ------------------------------------ --- 33.5/36.5 MB 10.9 MB/s eta 0:00:01
   ------------------------------------- -- 34.1/36.5 MB 11.1 MB/s eta 0:00:01
   ------------------------------------- -- 34.7/36.5 MB 11.7 MB/s eta 0:00:01
   -------------------------------------- - 35.3/36.5 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  35.7/36.5 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  36.0/36.5 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  36.5/36.5 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  36.5/36.5 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 9.8 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: D:\Python_DataScience\25.2\nibm_nic_env\Scripts\python.exe -m pip install --upgrade pip

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2) # 20% is allocated for the testing

In [15]:
model.fit(X_train,y_train,epochs=100,batch_size=10)

Epoch 1/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5261 - loss: 0.8839
Epoch 2/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6433 - loss: 0.6909
Epoch 3/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6450 - loss: 0.6734
Epoch 4/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6515 - loss: 0.6595
Epoch 5/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6492
Epoch 6/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6922 - loss: 0.6242
Epoch 7/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6710 - loss: 0.6159
Epoch 8/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6759 - loss: 0.6074
Epoch 9/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6857 - loss: 0.6212
Epoch 10/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7085 - loss: 0.5959
Epoch 11/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7003 - loss: 0.5920
Epoch 12/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7231 - loss: 0.5661
Epoch 13/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7117 - loss: 0.5686
Epoch 14/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7215 - loss: 0.5651
Epoch 15/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6938 - loss: 0.5748
Epoch 16/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7362 - loss: 0.5506
Epoch 17/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7248 - loss: 0.5455
Epoch 18/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7296 - loss: 0.5442
Epoch 19/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7345 - loss: 0.5348
Epoch 20/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7378 - loss: 0.5280
Epoch 21/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7524 - loss: 0.5188
Epoch 22/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7345 - loss: 0.5366
Epoch 23/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7329 - loss: 0.5289
Epoch 24/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7410 - loss: 0.5218
Epoch 25/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7427 - loss: 0.5135
Epoch 26/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7443 - loss: 0.5067
Epoch 27/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7443 - loss: 0.5045
Epoch 28/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7215 - loss: 0.5205
Epoch 29/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7492 - loss: 0.5047
Epoch 30/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7459 - loss: 0.4943
Epoch 31/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7362 - loss: 0.5143
Epoch 32/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7524 - loss: 0.5085
Epoch 33/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.4952
Epoch 34/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7443 - loss: 0.5129
Epoch 35/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7606 - loss: 0.4824
Epoch 36/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7769 - loss: 0.5060
Epoch 37/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7720 - loss: 0.4892
Epoch 38/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7508 - loss: 0.4935
Epoch 39/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7606 - loss: 0.4862
Epoch 40/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7394 - loss: 0.5208
Epoch 41/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.4965
Epoch 42/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7508 - loss: 0.4902
Epoch 43/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.4815
Epoch 44/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7541 - loss: 0.4825
Epoch 45/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7557 - loss: 0.4910
Epoch 46/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7476 - loss: 0.4877
Epoch 47/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7671 - loss: 0.4810
Epoch 48/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4775
Epoch 49/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7687 - loss: 0.4750
Epoch 50/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7720 - loss: 0.4771
Epoch 51/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7459 - loss: 0.5001
Epoch 52/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7638 - loss: 0.4749
Epoch 53/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7541 - loss: 0.4758
Epoch 54/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7752 - loss: 0.4814
Epoch 55/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7573 - loss: 0.4829
Epoch 56/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7752 - loss: 0.4663
Epoch 57/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7671 - loss: 0.4674
Epoch 58/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7638 - loss: 0.4845
Epoch 59/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7687 - loss: 0.4668
Epoch 60/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4677
Epoch 61/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7720 - loss: 0.4712
Epoch 62/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.4670
Epoch 63/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7704 - loss: 0.4573
Epoch 64/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7394 - loss: 0.4859
Epoch 65/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.4650
Epoch 66/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7752 - loss: 0.4686
Epoch 67/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.4676
Epoch 68/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7687 - loss: 0.4585
Epoch 69/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7638 - loss: 0.4721
Epoch 70/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7687 - loss: 0.4631
Epoch 71/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7687 - loss: 0.4625
Epoch 72/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4675
Epoch 73/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4565
Epoch 74/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7557 - loss: 0.4673
Epoch 75/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7443 - loss: 0.4869
Epoch 76/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4648
Epoch 77/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7638 - loss: 0.4635
Epoch 78/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7720 - loss: 0.4702
Epoch 79/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7704 - loss: 0.4614
Epoch 80/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7573 - loss: 0.4643
Epoch 81/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7671 - loss: 0.4603
Epoch 82/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7736 - loss: 0.4561
Epoch 83/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7638 - loss: 0.4669
Epoch 84/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7736 - loss: 0.4623
Epoch 85/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.4690
Epoch 86/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7638 - loss: 0.4595
Epoch 87/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7752 - loss: 0.4626
Epoch 88/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7655 - loss: 0.4515
Epoch 89/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7671 - loss: 0.4550
Epoch 90/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7606 - loss: 0.4583
Epoch 91/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7655 - loss: 0.4565
Epoch 92/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7769 - loss: 0.4548
Epoch 93/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7606 - loss: 0.4558
Epoch 94/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7704 - loss: 0.4511
Epoch 95/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7752 - loss: 0.4585
Epoch 96/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7541 - loss: 0.4703
Epoch 97/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7671 - loss: 0.4594
Epoch 98/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.4576
Epoch 99/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7704 - loss: 0.4511
Epoch 100/100
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7606 - loss: 0.4530

In [16]:
scores=model.evaluate(X_test,y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7078 - loss: 0.5468

In [17]:
print(model.metrics_names[1],scores[1]*100)

compile_metrics 70.77922224998474

In [18]:
print(model.metrics_names[0],scores[0]*100)

loss 54.68167066574097

In [19]:
model.predict(X_test[11:22])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

array([[0.28263155],
       [0.46865326],
       [0.20527016],
       [0.10282014],
       [0.5411407 ],
       [0.29607445],
       [0.3471231 ],
       [0.08877682],
       [0.02236127],
       [0.05636903],
       [0.25604016]], dtype=float32)